"""Public, flat top-level API of libdamp.

This module is the single source of truth for a flat namespace (``libdamp.RMSLoss`` etc.).
It must be changed if a name is added to, removed from, or renamed in a subpackage's public surface.

Note that :mod:`libdamp.generators` and :mod:`libdamp.processors` are not re-exported
here and remain accessible only through their own sub-namespace (e.g. `libdamp.generators.SinusoidalOsc`).
"""

from .augment import Augmentation, DropoutArtifactAugmentation, NoiseArtifactAugmentation, NoiseAugmentation
from .datasets import (
    CombinedDataset,
    ExcerptsDataset,
    MDBSynthDataset,
    NSynthDataset,
    PulseItDataset,
    SignalF0ExcerptsDataset,
    SyntheticSinusoidsDataset,
    ZipDataset,
)
from .experiment import Experiment
from .helpers import (
    OCTAVE_BANDS,
    THIRD_OCTAVE_BANDS,
    Convolution,
    ConvStack,
    FreqToBins,
    LogitsToFreq,
    SelectItem,
    apply_along_dim,
    combined_freqz,
    cubic_hermite_splines,
    design_butter_bandpass,
    design_butter_filter,
    design_fir_filter,
    design_resonant_filter,
    ensure_tensor,
    exp_sigmoid,
    freqz,
    get_window,
    hilbert,
    hz2midi,
    iir_freq_sampling,
    incremental_mod,
    interpolate_linear,
    interpolate_pchip,
    interpolate_samples,
    istft,
    midi2hz,
    poly,
    smooth,
    stft,
    tensor_linspace,
    timbre2harmonics,
)
from .losses import MSSLoss, RMSLoss
from .models import BasicBlock, BiLSTM, ResNet, resnet18

__all__ = [
    "Augmentation",
    "NoiseAugmentation",
    "DropoutArtifactAugmentation",
    "NoiseArtifactAugmentation",
    "Experiment",
    "CombinedDataset",
    "ZipDataset",
    "ExcerptsDataset",
    "SignalF0ExcerptsDataset",
    "MDBSynthDataset",
    "NSynthDataset",
    "PulseItDataset",
    "SyntheticSinusoidsDataset",
    "Convolution",
    "THIRD_OCTAVE_BANDS",
    "OCTAVE_BANDS",
    "freqz",
    "combined_freqz",
    "design_resonant_filter",
    "design_butter_bandpass",
    "design_butter_filter",
    "design_fir_filter",
    "iir_freq_sampling",
    "hz2midi",
    "midi2hz",
    "timbre2harmonics",
    "incremental_mod",
    "SelectItem",
    "ConvStack",
    "FreqToBins",
    "LogitsToFreq",
    "exp_sigmoid",
    "tensor_linspace",
    "apply_along_dim",
    "ensure_tensor",
    "interpolate_samples",
    "smooth",
    "cubic_hermite_splines",
    "interpolate_pchip",
    "interpolate_linear",
    "poly",
    "get_window",
    "stft",
    "istft",
    "hilbert",
    "RMSLoss",
    "MSSLoss",
    "BiLSTM",
    "BasicBlock",
    "ResNet",
    "resnet18",
]
